name: Update gist with WakaTime summary
on: [push]
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: superman66/wakatime-sync@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID}}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
